[package]
name = "rust-opengl-glutin-glow"
version = "0.1.0"
edition = "2021"

[features]
gl_matrix = []
glam = []
glm = []
cgmath = []

[dependencies]
glutin = "*"
glow = "*"
gl_matrix = "*"
glam = "*"
glm = "*"
cgmath = "*"
